features=["InternetService", "month", "Contract", "PaymentMethod", "tenure", "MonthlyCharges"]
target="Churn"
test_size=0.2

[random_forest]
n_estimators=250
max_depth=15
n_jobs=-1
random_state=83
bootstrap=false