name: casestudy-env
dependencies:
  - python=3.8
  - pip=19.3.1
  - pip:
    - jupyter==1.0.0
    - jupyterlab==3.2.5
    - pandas==1.0.0
    - scikit-learn==0.22.1
    - numpy==1.18.1
    - matplotlib==3.1.3
    - seaborn==0.10.0
    - black==19.10b0
    - toml==0.10.0
    - nose==1.3.7
    - phik
    - toml
